### ISSUE TITLE
.sln has incorrect path.

### ISSUE THREAD

**Issue by miou-gh** [Decagon/Spider#1]
Inside of the .sln file, the configuration is set to load the .csproj from "EventDebugEE\", it should be changed to "Spider\".

This can be easily done with just notepad.

**Comment by alexyorke** [comment]
Thanks for reporting this! I'll have to take a look at that.

**Comment by alexyorke** [comment]
I fixed this, but for some reason I can't push the changes. I'll investigate the issue.

**Comment by alexyorke** [comment]
I think I fixed this; I'll close in a week if nobody says otherwise.
